package com.gadarts.minesweeper.systems

enum class SystemEvents {
    PLAYER_BEGIN,
    PLAYER_INITIATED_MOVE,
    PLAYER_LANDED,
    PLAYER_BLOWN,
    PLAYER_IS_ABOUT_TO_BE_REMOVED,
    PLAYER_PICKED_UP_BONUS,
    MINE_TRIGGERED,
    TILE_REVEALED,
    PLAYER_PHYSICS_HARD_LAND,
    POWERUP_BUTTON_CLICKED,
    POWERUP_ACTIVATED,
    SHIELD_CONSUME,
    MAP_RESET;


}
