package com.gadarts.minesweeper.systems

enum class SystemEvents {
    PLAYER_BEGIN,
    PLAYER_INITIATED_MOVE,
    PLAYER_LANDED,
    PLAYER_BLOWN,
    MINE_TRIGGERED,
    CURRENT_TILE_VALUE_CALCULATED,
    PLAYER_PHYSICS_HARD_LAND,
    POWERUP_BUTTON_CLICKED,
    POWERUP_ACTIVATED,
    SHIELD_CONSUME,
    MAP_RESET;


}
